### ISSUE TITLE
Contenidos de la lista del header

### ISSUE THREAD

**Issue by Juamapa0** [Juamapa0/Neluanes#1]
1-Si cambio minúscula por mayúscula me cambia el diseño, quiero mantener el mismo diseño pero con mayúsculas.
2-Cómo separar el item "Cuenta" del resto para posicionarlo a la derecha.
3-Cómo alinear Cuenta y la imagen del carrito.
4-Cómo posicionar input y button a la derecha sin hacerlo a ojo.

**Comment by hipercubus** [comment]
te los paso a distintos issues, esa es la idea, de que cada cosa tenga su seguimiento
