### ISSUE TITLE
Otras correcciones generales

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#10]
- En el estilo del card usaste **cursor:pointer** (para que se vea el dedito) pero en realidad todo el contenido del card tendria que estar adentro de un **\<a>\</a>** ya que el card es un link que te va a abrir el detalle del producto
- Sigo viendo en el código mucha alineación a ojo. Eso lo tenes que volar TODO. 

> por ejemplo este **margin:42px** que no se que función cumple

![Captura de Pantalla 2022-07-15 a la(s) 09 35 02](https://user-images.githubusercontent.com/2010536/179224725-487209b4-43f6-4964-8f40-84d4866f9049.png)

> otro ejemplo, el card tiene un **width:64px** y el grid template es de **18rem**, eso no coincide y por eso te suma ese espacio extra a la derecha

![Captura de Pantalla 2022-07-15 a la(s) 09 45 31](https://user-images.githubusercontent.com/2010536/179226103-48195dcd-b2c2-42fb-a396-badc57037b73.png)

> pensá que todo lo que esta centrado a ojo se tiene que poder hacer de otra forma

**Comment by hipercubus** [comment]
Otra que vi, \<header> \<main> y \<footer> tiene un height de 30% 60% y 10% respectivamente. 
Eso no genera nada, pensá que sería el 60% de que?

**Comment by Juamapa0** [comment]
¿Tendría que ser respecto al html? del html un 60%...

**Comment by hipercubus** [comment]
> ¿Tendría que ser respecto al html? del html un 60%...

no no, no hay porcentaje del alto porque el alto es variable, lo determinan los contenidos
por eso no cambia nada pongas lo que pongas, no sirve para nada

**Comment by hipercubus** [comment]
> Los números en verde ¿cómo los leo?
a eso no le des bola, yo te estoy mostrando el espacio de mas que hay a la derecha

**Comment by Juamapa0** [comment]
No puse las cards dentro de la <a>, no me decidí aun si eso implica a la imagen o al div

**Comment by hipercubus** [comment]
> No puse las cards dentro de la , no me decidí aun si eso implica a la imagen o al div

el link tiene que envolver todo el contenido del card, si lo pones solo en la foto, cuando clickees en el texto no va a hacer nada y es confuso eso. 

* div del card
* * link a
* * * foto
* * * textos 
* * cierra link
* cierra div

**Comment by Juamapa0** [comment]
Si está bien incluida la etiqueta <a> , estarían resueltos estos problemas.

**Comment by hipercubus** [comment]
esto ya está todo, cierro el ticket
