### ISSUE TITLE
Que es esto?

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#11]
No se que son esas etiquetas \<enlace> pero creo que estan de mas

![Captura de Pantalla 2022-07-19 a la(s) 18 02 41](https://user-images.githubusercontent.com/2010536/179850865-0cf5f65f-c9f2-472b-b0e4-95d8e6c7d09a.png)

**Comment by Juamapa0** [comment]
Las fuentes  mal copiadas, trendía que decir link

**Comment by Juamapa0** [comment]
Cambié enlace por link y borre donde dice preconectar

**Comment by hipercubus** [comment]
Pero ya hay un \<link con la fuente en \<head, esos ahi creo que estan de más 
Sacalos y proba

**Comment by Juamapa0** [comment]
Estoy probando eso y si saco todas las fuentes no cambia nada.
Lo que si cambió es que se juntaron las palabras

**Comment by Juamapa0** [comment]
Volví a pegar los links, había puesto el traductor por eso aparecía enlace
