### ISSUE TITLE
Links pegados

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#12]
![Captura de Pantalla 2022-07-20 a la(s) 08 53 18](https://user-images.githubusercontent.com/2010536/179975651-974f4301-064d-40b0-a28d-bc3e2adf9dea.png)

Te quedaron los links pegados. Eso es un flex asi que lo arreglas con gap: 10px o lo que quieras

**Comment by Juamapa0** [comment]
Ahí le agregué el gap

**Comment by hipercubus** [comment]
listo, cierro
