### ISSUE TITLE
Posición del item Cuenta

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#3]
Cómo separar el item "Cuenta" del resto para posicionarlo a la derecha.

**Comment by hipercubus** [comment]
Cómo lo querés separar? Vos tenes todos los items centrados... querés que te queden todos a la derecha y cuenta a la izquierda?

**Comment by Juamapa0** [comment]
Si, https://www.coolmaison.com/, tomé esa página como ejemplo.

**Comment by hipercubus** [comment]
Ok perfecto. Varias cosas:

- El \<section> tiene un margin-left: 200px, Eso sacalo, tenés que evitar hacer esos ajustes manuales
- Dentro del \<section> tenes un \<nav> que no está ocupando el 100%, asi que agregale width: 100%, sino se ajusta al contenido y lo que vos queres es que se ajuste al ancho total
- Dentro del \<nav> tenes un \<ul> con varios \<li>, y los \<li> tienen un ancho predeterminado. Lo que tendrias que hacer es agregar un \<li> vacio donde queres que este la separacion, y a ese /<li> especificamente ponere un estilo con flex-grow: 1. Eso hace que ese \<li> se estire

![Captura de Pantalla 2022-07-12 a la(s) 15 24 59](https://user-images.githubusercontent.com/2010536/178569273-f1c4456c-f613-4087-98d0-5e7dc94e9cbf.png)
![Captura de Pantalla 2022-07-12 a la(s) 15 41 13](https://user-images.githubusercontent.com/2010536/178570054-c846b4a4-2c8e-4c53-8184-236808c18712.png)
