### ISSUE TITLE
Contador

### ISSUE THREAD

**Issue by Juamapa0** [Juamapa0/Neluanes#6]
Me faltaba el contador , se lo agregue al lado del carrito.
Me queda la duda si  la forma de agregarlo es con la etiqueta de span .

**Comment by hipercubus** [comment]
Con un span estaría bien, si no queres que ocupe un ancho fijo

**Comment by Juamapa0** [comment]
Lo que no consigo hacer es ubicar el contador a la derecha del carrito y manejar las distancias entre el contador , el carrito y cuenta.

**Comment by Juamapa0** [comment]
Cambíe algunas medidas que estaban en px por rem

**Comment by Juamapa0** [comment]
No me quedan cosas por resolver, que yo vea que tengo que resolver.
Al menos en este formato.

**Comment by Juamapa0** [comment]
margin-right:86px se lo saqué a nav .nav-center a, que es el que lo tenía, me quedó bien cuenta y mal lo otro que se juntó a la izquierda

**Comment by hipercubus** [comment]
> No me quedan cosas por resolver, que yo vea que tengo que resolver.
Al menos en este formato.

si queres te hago un par de observaciones de cosas que podrias mejorar, 
y sino ya tenes que ir a javascript, a automatizar todo lo que tenes

**Comment by Juamapa0** [comment]
Dale, espero tus observaciones, 
(quedó bien cuenta y mal lo otro que se juntó a la izquierda)

**Comment by Juamapa0** [comment]
Retoque en header, no me gusta como quedaron centrados los textos.
No lo toco más hasta que lo veas.

**Comment by hipercubus** [comment]
te hago otros issues con observaciones en comparacion con la pagina de https://www.coolmaison.com/
los isues que ya estan cerralos

**Comment by hipercubus** [comment]
este se puede cerrar?

**Comment by Juamapa0** [comment]
si
