### ISSUE TITLE
Contenedor

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#7]
Fijate como en CoolMaison tienen los contenedores de header main footer todos con el mismo ancho

![Captura de Pantalla 2022-07-15 a la(s) 08 47 53](https://user-images.githubusercontent.com/2010536/179217647-7f0004bc-6fd2-46df-908f-bc15f89b7763.png)

**Comment by Juamapa0** [comment]
Le agregue margin left y rigth, al no tener una imagen de ese tamaño me cambia todo.

**Comment by hipercubus** [comment]
No es una buena solucion usar margenes. Depende del ancho de la ventana te van a pasar cosas como esta:
![Captura de Pantalla 2022-07-19 a la(s) 17 57 36](https://user-images.githubusercontent.com/2010536/179847158-4f20b43a-97d5-4679-8187-23a83ca4bce2.png)
> Aparte agregás un espacio blanco fijo de cada lado que no es necesario y te va a complicar el escalado.

Tenes que volar todos esos margin left/right trabajar con containers de ancho fijo y margin: auto (eso te centra el container con el ancho que vos le das)

> Al header:
![Captura de Pantalla 2022-07-19 a la(s) 18 11 14](https://user-images.githubusercontent.com/2010536/179849403-b02004af-2d70-49a7-84c4-352afaf4d635.png)

> Al main:
![Captura de Pantalla 2022-07-19 a la(s) 18 11 20](https://user-images.githubusercontent.com/2010536/179849609-1431c0a1-1fa8-49f6-914a-615903ce53f1.png)

> Al cards-container cambiale el justify-content asi las cards te ocupan todo el ancho
![Captura de Pantalla 2022-07-19 a la(s) 18 11 32](https://user-images.githubusercontent.com/2010536/179849842-a2244ffb-4d34-4ba3-9a8c-3cc9936b2cf0.png)

> Al footer: 
![Captura de Pantalla 2022-07-19 a la(s) 18 14 57](https://user-images.githubusercontent.com/2010536/179849716-90cf4c5c-740d-46e3-99db-de740fef2ab5.png)

Y ahi te va a quedar todo bien alineado:

![Captura de Pantalla 2022-07-19 a la(s) 18 12 42](https://user-images.githubusercontent.com/2010536/179849946-55530c37-4226-44b0-99ce-4655ee839562.png)

**Comment by hipercubus** [comment]
este ya lo cerraste? quedo bien?

**Comment by hipercubus** [comment]
yo sigo viendo mal esto, no se si te falta pushear

**Comment by Juamapa0** [comment]
Me falta el push

**Comment by Juamapa0** [comment]
Listo
