### ISSUE TITLE
Card - Temas de diseño

### ISSUE THREAD

**Issue by hipercubus** [Juamapa0/Neluanes#9]
- Yo laburaría un poco mas los textos de la tarjeta, como para que tenga una jerarquía 
- Aca fijate que ya de base use un gris #555555 en vez de negro puro, y para el precio un poco mas claro
- También le meti cambios de tamaño a los tres niveles
- ... y no tan separados
![Captura de Pantalla 2022-07-15 a la(s) 09 17 34](https://user-images.githubusercontent.com/2010536/179222958-fe1c69af-1362-464f-ab4b-6f7fa3c56dae.png)

> Aca probé otra variante con marco y border-radius
![Captura de Pantalla 2022-07-15 a la(s) 09 25 26](https://user-images.githubusercontent.com/2010536/179223138-a772cdf1-d59e-4398-8550-50f39b094a49.png)

**Comment by hipercubus** [comment]
Bueno... asi quedo muy bien.

Igualmente si queres probar te paso lo del borde. Probá con esto en el estilo de product-card
![Captura de Pantalla 2022-07-19 a la(s) 17 49 39](https://user-images.githubusercontent.com/2010536/179845948-8ccacf0a-0db2-42c5-88d3-a25c5483a2c6.png)

Ahi te va a quedar asi:
![Captura de Pantalla 2022-07-19 a la(s) 17 50 21](https://user-images.githubusercontent.com/2010536/179846027-2463e032-b2f9-487e-a262-45c0b0902a73.png)

Y para arreglar lo de la imagen cambiale el width a 100% en vez de 264px (asi se adapta al ancho que la contiene):
![Captura de Pantalla 2022-07-19 a la(s) 17 49 59](https://user-images.githubusercontent.com/2010536/179846333-d315d2dc-f1b3-49a7-8025-34a9a8941b2a.png)

Probalo como para también saber como se hace

**Comment by Juamapa0** [comment]
La verdad es que me gustan las dos opciones.
Lo dejo con el marco.

**Comment by hipercubus** [comment]
yo todavia lo veo sin marco, deja el ticket abierto hasta que ya este listo

**Comment by Juamapa0** [comment]
Miralo ahora

**Comment by hipercubus** [comment]
hermoso, cierro
